### ISSUE TITLE
Fix images

### ISSUE THREAD

**Issue by kyle534452** [StarLegacy/StarLegacy.Wiki#42]
I don’t know if this is a problem for everyone but for me and my friends who play star legacy the printer for example and various other sections have letters and numbers were there should be pictures so I suggest that you put in new pictures 

https://www.dropbox.com/sh/sy1yfb6usxi5c79/AAANpDUKfh4U6rJKjlLyrAJDa?dl=0

Pictures from Doctor Candy and kay on discord

**Comment by kyle534452** [comment]
https://www.dropbox.com/sh/sy1yfb6usxi5c79/AAANpDUKfh4U6rJKjlLyrAJDa?dl=0

**Comment by kyle534452** [comment]
Pictures ⬆️

**Comment by kyle534452** [comment]
Got pics from Doctor Candy on discord

**Comment by hafarooki** [comment]
https://github.com/StarLegacy/StarLegacy.Wiki/pull/41
